---
# MySQL Database Deployment - Optimizado para GKE
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: moodle
type: Opaque
data:
  mysql-root-password: bW9vZGxlMTIzNDU=  # moodle12345
  mysql-password: bW9vZGxlMTIzNDU=       # moodle12345
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: moodle
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: moodle
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: "moodle"
        - name: MYSQL_USER
          value: "moodle"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: MYSQL_CHARACTER_SET_SERVER
          value: "utf8mb4"
        - name: MYSQL_COLLATION_SERVER
          value: "utf8mb4_unicode_ci"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - -u
            - root
            - -p${MYSQL_ROOT_PASSWORD}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - -u
            - root
            - -p${MYSQL_ROOT_PASSWORD}
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: moodle
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql
  type: ClusterIP
---
# Moodle Application Deployment - Optimizado para GKE
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-data-pvc
  namespace: moodle
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
  namespace: moodle
  labels:
    app: moodle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
      - name: moodle
        image: bitnami/moodle:4.3.4
        ports:
        - containerPort: 8080
        env:
        - name: MOODLE_DATABASE_HOST
          value: "mysql"
        - name: MOODLE_DATABASE_PORT_NUMBER
          value: "3306"
        - name: MOODLE_DATABASE_NAME
          value: "moodle"
        - name: MOODLE_DATABASE_USER
          value: "moodle"
        - name: MOODLE_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: MOODLE_USERNAME
          value: "admin"
        - name: MOODLE_PASSWORD
          value: "moodle12345"
        - name: MOODLE_EMAIL
          value: "admin@moodle.local"
        - name: MOODLE_SITE_NAME
          value: "Campus Virtual GKE"
        - name: MOODLE_SKIP_BOOTSTRAP
          value: "no"
        - name: MOODLE_DATABASE_TYPE
          value: "mysqli"
        - name: MOODLE_ENABLE_HTTPS
          value: "no"
        - name: MOODLE_ENABLE_EMPTY_PASSWORD
          value: "no"
        - name: MOODLE_ENABLE_DATABASE_SSL
          value: "no"
        - name: MOODLE_EXTRA_INSTALL_ARGS
          value: "--allow-unstable"
        - name: MOODLE_SMTP_HOST
          value: ""
        - name: MOODLE_SMTP_PORT
          value: ""
        - name: MOODLE_SMTP_USER
          value: ""
        - name: MOODLE_SMTP_PASSWORD
          value: ""
        - name: MOODLE_SMTP_PROTOCOL
          value: ""
        volumeMounts:
        - name: moodle-data
          mountPath: /bitnami/moodle
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            httpHeaders:
            - name: Host
              value: localhost
          initialDelaySeconds: 120
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            httpHeaders:
            - name: Host
              value: localhost
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
      volumes:
      - name: moodle-data
        persistentVolumeClaim:
          claimName: moodle-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: moodle
  namespace: moodle
  labels:
    app: moodle
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: moodle
  sessionAffinity: None 