---
# ConfigMap para Moodle
apiVersion: v1
kind: ConfigMap
metadata:
  name: moodle-config
  namespace: moodle
data:
  ALLOW_EMPTY_PASSWORD: "no"
  MOODLE_DATABASE_HOST: 10.169.65.226
  MOODLE_DATABASE_NAME: moodle
  MOODLE_DATABASE_PASSWORD: 7s4bLvmszaV2CKjFd$ZV
  MOODLE_DATABASE_PORT_NUMBER: "3306"
  MOODLE_DATABASE_USER: root
  MOODLE_EMAIL: admin@telesalud.gob.sv
  MOODLE_ENABLE_HTTPS: "no"
  MOODLE_EXTRA_PHP_SETTINGS: |-
    memory_limit = 2G
    max_execution_time = 1800
    max_input_vars = 5000
  MOODLE_PASSWORD: Admin123!
  MOODLE_SITE_NAME: Moodle Telesalud
  MOODLE_SKIP_BOOTSTRAP: "no"
  MOODLE_USERNAME: admin
  MYSQL_CLIENT_SSL_MODE: DISABLED
  PHP_MAX_EXECUTION_TIME: "1800"
  PHP_MEMORY_LIMIT: 2G
  MOODLE_SKIP_INSTALL: "no"
  MOODLE_DATABASE_TYPE: mysqli
---
# PVC para datos de Moodle
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-data-pvc
  namespace: moodle
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 10Gi
---
# PVC para moodledata
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-moodledata-pvc
  namespace: moodle
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 20Gi
---
# Deployment de Moodle (versión simplificada)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
  namespace: moodle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
      - name: moodle
        image: bitnami/moodle:latest
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: moodle-config
        volumeMounts:
        - name: moodle-data
          mountPath: /bitnami/moodle
        - name: moodle-moodledata
          mountPath: /bitnami/moodledata
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /login/index.php
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /login/index.php
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
      volumes:
      - name: moodle-data
        persistentVolumeClaim:
          claimName: moodle-data-pvc
      - name: moodle-moodledata
        persistentVolumeClaim:
          claimName: moodle-moodledata-pvc
---
# Service para Moodle
apiVersion: v1
kind: Service
metadata:
  name: moodle-service
  namespace: moodle
spec:
  selector:
    app: moodle
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
    name: http
  - protocol: TCP
    port: 443
    targetPort: 8443
    nodePort: 30443
    name: https
  type: NodePort
---
# Ingress para Moodle
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moodle-service
  namespace: moodle
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "moodle-ip"
    kubernetes.io/ingress.class: "gce"
    ingress.gcp.kubernetes.io/ssl-redirect: "true"
spec:
  defaultBackend:
    service:
      name: moodle-service
      port:
        number: 80
  tls:
  - hosts:
    - campusvirtual.telesalud.gob.sv
    secretName: cloudflare-cert
  rules:
  - host: campusvirtual.telesalud.gob.sv
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: moodle-service
            port:
              number: 80 