apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-filestore-pvc
  namespace: moodle
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: filestore-rwx
  resources:
    requests:
      storage: 1024Gi 