apiVersion: v1
kind: Namespace
metadata:
  name: moodle
  labels:
    name: moodle
    app: moodle
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx 