# Default values for mysql
replicaCount: 1

image:
  repository: bitnami/mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 1001

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1001

service:
  type: ClusterIP
  port: 3306

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  storageClass: "standard-rwo"
  size: 20Gi
  accessMode: ReadWriteOnce

mysql:
  rootPassword: ""
  database: moodle
  username: moodle
  password: ""
  port: 3306

env:
  - name: MYSQL_ROOT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mysql-secret
        key: root-password
  - name: MYSQL_DATABASE
    value: "{{ .Values.mysql.database }}"
  - name: MYSQL_USER
    value: "{{ .Values.mysql.username }}"
  - name: MYSQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mysql-secret
        key: password

nodeSelector: {}

tolerations: []

affinity: {} 