apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "moodle.fullname" . }}-config
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
data:
  MOODLE_SITENAME: {{ .Values.moodle.sitename | quote }}
  MOODLE_SITE_URL: {{ .Values.moodle.siteurl | quote }}
  MOODLE_DATABASE_TYPE: {{ .Values.database.type | quote }} 