apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  root-password: {{ .Values.mysql.rootPassword | b64enc | quote }}
  password: {{ .Values.mysql.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: moodle-db-secret
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.mysql.password | b64enc | quote }} 